import brisk
api = brisk.api(host="10.22.43.93", version="8.50.0.465")
cObj = api.config()
scObj = cObj.scenarios.scenario().scenario()
nwObj = scObj[0].networks.network(name="client")
nwObj1 = scObj[1].networks.network(name="server")
pObj = nwObj[0].protocols.protocol()
pObj2 = nwObj1[0].protocols.protocol()
hObj1 = pObj2[0].httpserver.httpserver(enable_tos=True)
hObj2 = pObj[0].httpclient.httpclient(enable_ssl=True)
cmdObj = hObj2[0].commands.command(command_type = "GET", destination = "Traffic2_HTTPServer1:80", page_object= "/1b.html")
etObj = nwObj[-1].ethernet.ethernet()
ipv4Obj = nwObj[-1].ipv4.ipv4()
ccObj = cObj.chassis.chassis(name="10.39.64.137")
pObj1 = nwObj[-1].ports.port(chassis_id=1, card_id=2, port_id=11)
pObj1 = nwObj1[-1].ports.port(chassis_id=1, card_id=2, port_id=12)
api.set_config(cObj)
print(api.run_test())
print(cObj)
print("*****")