openapi: 3.1.0

info:
  title: Emulated device property pattern models
  version: ^0.0.0

components:
  schemas:
    Device.Pattern:
      description: >-
        A container for emulated device property patterns.
      type: object
      required: [choice]
      properties:
        choice: 
          type: string
          enum: [value, values, increment, decrement]
        value:
          type: string
        values:
          type: array
          items:
            type: string
        increment:
          $ref: '#/components/schemas/Device.Counter'
        decrement:
          $ref: '#/components/schemas/Device.Counter'

    Device.Counter:
      description: >-
        An incrementing pattern.
      type: object
      properties:
        start:
          type: string
        step:
          type: string

